package com.projecta.notification.model;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    USER_REGISTERED,
    USER_PASSWORD_RESET,
    GENERAL_ALERT,
    PROMOTIONAL
}
