name: d.pullrequest
on:
  pull_request:
    types: [opened, reopened, synchronize, closed, ready_for_review, review_requested, labeled]
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run a script
        run: echo "Iam running pull req"
      - name: Iam checking
        run: echo "iam checking...."